site_name: Belajar PyTorch by McTosima
site_url: https://mctosima.github.io/belajarpytorch
site_description: Belajar PyTorch by McTosima

theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - 00. Apa itu PyTorch: 00_Apa_itu_pytorch.ipynb

plugins:
  - mkdocs-jupyter
  - search
  - social