site_name: Belajar PyTorch Berbahasa Indonesia
site_url: https://belajarpytorch.my.id
site_description: Belajar PyTorch Berbahasa Indonesia

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav:
  - Home: 'index.md'
  - 00. Pengantar: '00_Pengantar.ipynb'
  - 01. Hello World: '01_HelloWorldnyaDL.ipynb'
  - 02. Klasifikasi Sederhana: '02_KlasifikasiSederhana.ipynb'
  - 3. Klasifikasi Multi Kelas: '03_Multiclass.ipynb'
  - 4. Klasifikasi FashionMNIST: '04_FashionMNIST.ipynb'
  - Cheatsheet: 'cheatsheet.md'
  - Mempersiapkan PyTorch: 'instalasi.md'
  - Sumber Belajar: 'sumber.md'

plugins:
  - mkdocs-jupyter
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mctosima_
    - icon: fontawesome/brands/github
      link: https://github.com/mctosima/belajarpytorch
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mctosima
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@mctosima

  