site_name: Belajar PyTorch by McTosima
site_url: https://mctosima.github.io/belajarpytorch
site_description: Belajar PyTorch by McTosima

theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - 00. Getting Started with PyTorch: '00_pytorch_fundamentals.ipynb'